#ifndef HEADER_TYPES
#define HEADER_TYPES

#define TYPE_UNKNOWN 0
#define TYPE_PLAYER 1
#define TYPE_GRAVESTONE 2
#define TYPE_ZOMBIE 3
#define TYPE_PLAYER_BULLET 4
#define TYPE_GAME_SCENE 5
#define TYPE_BOARD 5
#define TYPE_LOG 6
#define TYPE_SCORE 7
#define TYPE_SKELETON 8
#define TYPE_BAT 9
#define TYPE_SCENE 10
#define TYPE_TEXT 11
#define TYPE_HEALTH 12
#define TYPE_SCROLLING_TEXT 13
#define TYPE_TITLE_SCENE 14
#define TYPE_GAME_OVER_SCENE 15
#define TYPE_WIN_SCENE 16
#define TYPE_CREDITS_SCENE 17
#define TYPE_SKELETON_BULLET 18

#define TYPE_COMPONENT_UNKNOWN 0
#define TYPE_COMPONENT_TRANSFORM_2D 1
#define TYPE_COMPONENT_NAME 2
#define TYPE_COMPONENT_PLAYER_MOVEMENT 3
#define TYPE_COMPONENT_PLAYER_FIRE_BULLET 4
#define TYPE_COMPONENT_BULLET_MOVEMENT 5
#define TYPE_COMPONENT_ZOMBIE 6
#define TYPE_COMPONENT_NCURSES_RENDER 7
#define TYPE_COMPONENT_RANDOM_MOVEMENT 8
#define TYPE_COMPONENT_SEEKING_MOVEMENT 9
#define TYPE_COMPONENT_MOVEMENT_COLLIDER 10
#define TYPE_COMPONENT_BOARD 11
#define TYPE_COMPONENT_LOG 12
#define TYPE_COMPONENT_SCORE 13
#define TYPE_COMPONENT_BULLET 14
#define TYPE_COMPONENT_GRAVESTONE 15
#define TYPE_COMPONENT_SKELETON 16
#define TYPE_COMPONENT_HITPOINTS 17
#define TYPE_COMPONENT_PLAYER 18
#define TYPE_COMPONENT_HEALTH 19
#define TYPE_COMPONENT_BAT 20
#define TYPE_COMPONENT_BAT_MOVEMENT 21
#define TYPE_COMPONENT_NCURSES_TEXT_RENDER 22
#define TYPE_COMPONENT_SCROLLING_MOVEMENT 23
#define TYPE_COMPONENT_TITLE_SCENE 24
#define TYPE_COMPONENT_GAME_OVER_SCENE 25
#define TYPE_COMPONENT_CREDITS_SCENE 26
#define TYPE_COMPONENT_RANDOM_UPDATE_SPAWNER 27
#define TYPE_COMPONENT_RANDOM_SETUP_SPAWNER 28

#endif
