name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get -y install libsdl2-dev libsdl2-mixer-dev libncurses-dev gcovr
    - name: install python deps
      run: pip install --user -r requirements.txt
    - name: bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure
    - name: make clean
      run: make clean
    - name: make
      run: make
    - name: make check
      run: make check
    - name: test log
      if: failure()
      run: cat tests/testsuite.log
